name: booking
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  get: "4.6.5"
  image_picker: "1.0.2"
  url_launcher: "6.1.1"
  permission_handler: "10.4.3"
  pull_to_refresh: "2.0.0"
  card_swiper: "3.0.1"
  easy_splash_screen: "1.0.4"
  sprintf: "7.0.0"
  email_validator: "2.1.17"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
